"""add price to table

Revision ID: bc6c15fef212
Revises: dfebf05670d1
Create Date: 2024-09-22 22:38:02.743802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bc6c15fef212'
down_revision: Union[str, None] = 'dfebf05670d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

accounts_table = sa.table(
    "policy",
    sa.column("id", sa.Integer),
    sa.column("title", sa.String),
    sa.column("date", sa.String),
    sa.column("type", sa.String),
    sa.column("name", sa.String),
    sa.column("wording", sa.String),
    sa.column("price", sa.Float),
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy', sa.Column('price', sa.Float(), nullable=False))
    policies_table = sa.table(
    "policy",
    sa.column("id", sa.Integer),
    sa.column("title", sa.String),
    sa.column("date", sa.String),
    sa.column("type", sa.String),
    sa.column("name", sa.String),
    sa.column("wording", sa.String),
    sa.column("price", sa.Float),
    )

    op.bulk_insert(
        policies_table,
        [
            {
                "id": 1,
                "title": "test title 1",
                "date": "2024-08-03",
                "type": "car",
                "name": "test name 1",
                "wording": "test wording 1",
                "price": 1234.89
            },
            {
                "id": 2,
                "title": "test title 2",
                "date": "2024-09-03",
                "type": "home",
                "name": "test name 2",
                "wording": "test wording 2",
                "price": 5432.90
            },
            {
                "id": 3,
                "title": "test title 3",
                "date": "2024-10-03",
                "type": "travel",
                "name": "test name 3",
                "wording": "test wording 3",
                "price": 300.33
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy', 'price')
    # ### end Alembic commands ###
